# Generated by Django 3.1.3 on 2020-11-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRating',
            fields=[
                ('MovieId', models.AutoField(primary_key=True, serialize=False)),
                ('MovieTitle', models.CharField(max_length=100)),
                ('ReleaseDate', models.DateField()),
                ('MovieImage', models.ImageField(upload_to='')),
                ('UpVotes', models.BigIntegerField()),
                ('DownVotes', models.BigIntegerField()),
                ('Rating', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
